### ISSUE TITLE
Search input stays expanded when you unfocus it

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-header#115]
Currently if you are focused in the search input, then you tab out of it, the focus moves to elements in the menu. But these are now obscured by the search input:

![image](https://cloud.githubusercontent.com/assets/250617/12515782/ddfcfd3a-c121-11e5-9261-7da5f1028be4.png)

The input should probably collapse (as if the user clicked the big cross) onblur.

**Comment by onishiweb** [comment]
I think this is kind of ok, because the next item that gets focused is the search icon, which if pressed closes the search. Unsure if someone tabbing away from the search form would be enough to signify they no longer wish to use it. In this case losing focus would trigger an action, however we don't open the search bar when a user tabs to the search icon...

/ @AlbertoElias @alicebartlett any thoughts?

**Comment by onishiweb** [comment]
Fix tab order:
- search input > search button > close button
- allow tab index to get to something else between input and search button

Don't close search bar on blur.

**Comment by onishiweb** [comment]
@alicebartlett going to close this issue too.
