### ISSUE TITLE
Subnav in S layout

### ISSUE THREAD

**Issue by andygout** [Financial-Times/o-header#150]
- [ ] Subnav opens on top of hamburger icon, making it difficult to identify how to close subnav menu.
- [ ] Still possible to scroll down entire page while subnav open when it should be locked in place when opening at this layout width.
- [ ] z-index issues (quick fix (for front-page) would be `z-index: 2`; poss. better in long run to start employing https://github.com/Financial-Times/next-sass-setup/blob/58466d840edbc4fda2bf6dae1eaa1ca95920f08c/_z-indexes.scss).
- [ ] Font sizes smaller than current.
- [ ] Changed background colour from current.
- [ ] Cannot open submenus from headers (i.e. World/UK/Companies).

Browsers: Chrome (v49.0.2623.87); Firefox (v44.0.2); Safari (9.0.3); IE9-11

##### Current live
![current-header](https://cloud.githubusercontent.com/assets/10484515/13951419/bdb02670-f028-11e5-8b1e-f32df2ddf102.png)

##### v.5.0.0-beta.9
![new-header](https://cloud.githubusercontent.com/assets/10484515/13951424/c151849a-f028-11e5-99a0-89bc1e5e6331.png)

**Comment by AlbertoElias** [comment]
Just noticed a bug in beta 9 which I'm fixing, though your header looks really broken in that image, so would be good to talk about that in person.

Should the font size be the same as the original?
The colour changed because the one being used wasn't in the palette, so I spoke with George and found another one in the palette. Ended up leaving it as pink to be consistent with the light theme

**Comment by AlbertoElias** [comment]
1. Seems to be a Next bug
2. Next beta will fix
3. Next beta plus Next using new `o-header-z-index` Sass variable will fix
4. Fixed in next beta
5. This is supposed to be like that
6. Fixed in next beta

Will close this when next beta is released

**Comment by AlbertoElias** [comment]
Fixed in beta 10
