### ISSUE TITLE
Core experience

### ISSUE THREAD

**Issue by dan-searle** [Financial-Times/o-header#19]
How do we handle core experience?

The following are JS-dependent:

* 'squishiness' (priority-based hiding of top-level nav items when horizontal space doesn't allow)
* Expand/collapse of dropdowns and mega-dropdowns

I think @pauloneillft and @danskinner favour a fragment link to a simple list of sections/tools at the foot of the page.

**Comment by kaelig** [comment]
Because there are many ways of implementing the footer (with or without a mega navigation), products themselves should choose, if applicable, to build in a better core experience for browsers that have JS disabled or don't cut the mustard.

Basically we provide decent styling for the header when JS doesn't run but we can't tie it to the footer without creating a potential barrier for adoption.
