### ISSUE TITLE
Separate Sub-Nav items

### ISSUE THREAD

**Issue by alexnaish** [Financial-Times/o-header#376]
Feature Request

## What

We have had a feature request from UX to separate specific items in the sub-navigation. Specific items should be right aligned and be more obvious as a link. Since theres quite a bit of logic around the handling of responsive display of the items it'd be good to talk through solutions.

## Details

Requested Functionality:

![Screenshot 2020-04-21 at 11 59 32](https://user-images.githubusercontent.com/6599523/79873824-8aedb000-83df-11ea-9752-1738ca0ab4d7.png)

Current:
![Screenshot 2020-04-21 at 10 13 42](https://user-images.githubusercontent.com/6599523/79873829-8c1edd00-83df-11ea-8a74-96c7992465a9.png)

The key sections on the above screnshots is the placement of the "Administration" link. Since its not really a section of my account, we want to make a clearer distinction between it and the others

**Comment by notlee** [comment]
Thanks Alex, yeah this should definitely be an o-header change. We should also add it as a pattern in the Product Design Sketch Toolkit and document, I'll loop in Luke Griffiths.

Questions that spring to mind:

1. The current "personal details" link in the subnav is missing the teal underline. Is that intentional?

2. Other ft.com pages put the current page into the breadcrumb, and don't show a subnav if there is no further pages. Here "personal details" doesn't go into the breadcrumb and the other sibling pages are still visible. I'm guessing that's so users can more easily navigate all their settings and accounts in one session but would like to confirm the design thinking so we can document when to use one pattern over the other. :)
<img width="1210" alt="Screenshot 2020-04-22 at 09 26 50" src="https://user-images.githubusercontent.com/10405691/79959211-c3db6280-847b-11ea-8851-3716f7b09ef8.png">

3. At the moment the whole subnav becomes scrollable when it overflows. How do these new right aligned links work in this case?
<img width="769" alt="Screenshot 2020-04-22 at 09 30 16" src="https://user-images.githubusercontent.com/10405691/79959327-e5d4e500-847b-11ea-9a4e-7ec4f3ee22ab.png">

4. If we are giving the right aligned items underlines, should the "portfolio" and "settings & account" get underlines too? I'd worry that would look to busy but also am unsure if it makes sense for only some items to get an underline.

**Comment by alexnaish** [comment]
1) I think we can ignore it for now but it's probably a question for Olga (@belkinsson). 

2) Yeah this is less to do with the hierarchy of pages and more to do with an easier navigation between sections as you said!

3) That was one of the main reasons I wanted to raise it here - there seems to be quite a lot of specific styling around the laying out of the items, as well as any JS involved to calculate scroll direction, widths etc and the last thing I wanted to do was to break that! I imagined that the right aligned links would be spaced out as long as there was enough width to allow it otherwise it fits into what space is available. For example:

```
.c {
  display: flex;
  flex-direction: row;
}

.item--spaced {
  margin-left: auto;
}
```

4) Definitely one for Olga!

**Comment by notlee** [comment]
Cool, it would be good to get Olga's thoughts on 3 too :)

**Comment by alexnaish** [comment]
I've sent the link to Olga on slack so we should be able to get a clearer direction once she has weighed in!

**Comment by notlee** [comment]
Hmm, looking closer we don't show a signout link in the subnav anywhere else, is it useful for users here? If it's there mostly to facilitate the "Administration" link being floated right, I'm wondering if there are alternative options for where to direct users to the "Administration"  page? It would be awesome if we could save ourselves maintaining a new header pattern in code and the design toolkit!

**Comment by belkinsson** [comment]
1. Strange, but I can see the underline now.
<img width="1233" alt="Screenshot 2020-04-22 at 17 05 00" src="https://user-images.githubusercontent.com/18575357/80005779-f9a03b80-84bb-11ea-93ec-7439611cbc2a.png">
2. Yes :)
3. Good question, I will think and mock this up. (Generally agree with Alex's comment)
4. Good point, I think we need to maintain the consistency and keep the same
pattern + hover over, I will tweak the design.
5. @notlee As far as I know it currently shows as Sign in because of Sandbox limitation. Again,
I'm not sure where it will be once live - the Content Nav (Home, world) Or in Settings & Account @alexnaish ? (Screenshot above)

**Comment by notlee** [comment]
Thanks @belkinsson! If the signin link would make sense in the content nav, do you think the "Administration" link should still be floated right on its own? If there's an alternative place it could live that would make sense for users it would be great to avoid adding complexity to o-header

**Comment by notlee** [comment]
Just chatted to Olga. They're considering the above and will discuss in the Design Forum meeting

**Comment by belkinsson** [comment]
Number of users (from B2B): "Looking at the report I generated (  I hope it's correct ), we have around 9,270 LAs from the active licences we have".
Raising this with the team to understand if it's small/large enough group of users.

**Comment by notlee** [comment]
Olga informs me we can close this ticket. I _think_ they have spoken to the Accounts team and concluded it's not necessary

**Comment by notlee** [comment]
We've returned to this issue after feedback from users that the signout link is difficult to find. 

One alternative approach was to add a [new signout icon](https://github.com/Financial-Times/fticons/pull/102) next to the signout subnav item. However the preferred approach is to add right aligned subnav items to `o-header` instead, inline with the main nav settings & account link above ([see Slack](https://financialtimes.slack.com/archives/C01481FKWA2/p1598027970002400)).

To achieve this we need to update `o-header` and make a small markup change in the relevant Customer Products project -- perhaps via PageKit
