### ISSUE TITLE
nav selected states and dropdown styling

### ISSUE THREAD

**Issue by pauloneillft** [Financial-Times/o-header#78]
![org011-overview_v14 fw](https://cloud.githubusercontent.com/assets/3977053/4089490/ef9874ea-2f6c-11e4-8b16-df92ef7f8348.png)

<i>Proposal</i> for how they should work. 

It's basically a background white on the nav item with transparency 0.2. 

There's also a recommendation for how dropdowns should work. They exist in the current release but need proper designing. 

If all are happy with this. I can spec it out in a pencil sketch describing widths, heights, fonts, distances etc to help build.

**Comment by kaelig** [comment]
Header sub menus depend on logic behind hierarchical nav and squishy list. They're pretty limiting but it encourages to aim for simplicity which is better for mobile.

Products that needed a different navigation system have used alternative ways to achieve sub menus.

Since we can't measure the impact of changes on sub navigation and that the Next FT navigation is coming this year with major changes, we chose not to invest time on fixing these navigation limitations.
